### ISSUE TITLE
Animations for MapEntityStatic Are Not Working As Intended

### ISSUE THREAD

**Issue by mlcgaming** [mlc-game-design/London#2]
CurrentFrame on MapEntityStatic objects are jumping from 0 to 2 back to 0, rather than moving progressively by 1 to FrameCount.  Test Torches on DungeonMap_StarCave_1F can be used for visual reference.

**Comment by MCourneya** [comment]
Pointer value was causing double Updates from MapEntitiesStatic objects. Changed CreateAnimationDictionary method to instead perform a ToDictionary cloning process.
